<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>SurvivalSymmetryRenderer</RootNamespace>
    <AssemblyName>SurvivalSymmetryRenderer</AssemblyName>
    <LangVersion>14</LangVersion>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('Windows'))">net48;net10.0</TargetFrameworks>
    <TargetFramework Condition="!$([MSBuild]::IsOSPlatform('Windows'))">net10.0</TargetFramework>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <PlatformTarget>x64</PlatformTarget>
    <DefineConstants>TRACE;PULSAR;LOCAL_BUILD</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Sandbox.Game">
      <HintPath>$(Bin64)\Sandbox.Game.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Sandbox.Common">
      <HintPath>$(Bin64)\Sandbox.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="NLog">
      <HintPath>$(Bin64)\NLog.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VRage">
      <HintPath>$(Bin64)\VRage.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VRage.Game">
      <HintPath>$(Bin64)\VRage.Game.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VRage.Library">
      <HintPath>$(Bin64)\VRage.Library.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VRage.Math">
      <HintPath>$(Bin64)\VRage.Math.dll</HintPath>
      <Private>False</Private>
    </Reference>
      <Reference Include="0Harmony">
      <HintPath>$(Bin64)\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>
    <PublicizerRuntimeStrategies>Unsafe;IgnoresAccessChecksTo</PublicizerRuntimeStrategies>
    <PublicizerLogFilePath>$(MSBuildProjectDirectory)\Krafs.Publicizer.$(TargetFramework).log</PublicizerLogFilePath>
  </PropertyGroup>

  <ItemGroup>
    <Publicize Include="Sandbox.Game"/>
  </ItemGroup>
</Project>
